// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EvPlugNet1.Models;

public partial class ChargePointNode
{
    public int Id { get; set; }

    public int? NodeId { get; set; }

    public string ChargePointId { get; set; }

    public DateTime DateCreate { get; set; }
}