// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EvPlugNet1.Models;

public partial class ChargePoint
{
    public string ChargePointId { get; set; }

    public string Name { get; set; }

    public string Comment { get; set; }

    public string Username { get; set; }

    public string Password { get; set; }

    public string ClientCertThumb { get; set; }

    public virtual ICollection<Transaction> Transactions { get; set; } = new List<Transaction>();
}