// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EvPlugNet1.Models;

public partial class ConnectorStatus
{
    public string ChargePointId { get; set; }

    public int ConnectorId { get; set; }

    public string ConnectorName { get; set; }

    public string LastStatus { get; set; }

    public DateTime? LastStatusTime { get; set; }

    public double? LastMeter { get; set; }

    public DateTime? LastMeterTime { get; set; }
}