// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EvPlugNet1.Models;

public partial class MessageLog
{
    public int LogId { get; set; }

    public DateTime LogTime { get; set; }

    public string ChargePointId { get; set; }

    public int? ConnectorId { get; set; }

    public string Message { get; set; }

    public string Result { get; set; }

    public string ErrorCode { get; set; }
}