// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EvPlugNet1.Models;

public partial class NodeType
{
    public int Id { get; set; }

    public string NodeType1 { get; set; }

    public DateTime Datedreate { get; set; }
}