// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EvPlugNet1.Models;

public partial class Nodes2charger
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int? Type { get; set; }

    public DateTime DateCreate { get; set; }

    public string StringLocation { get; set; }

    public string ChargePointId { get; set; }

    public int? SecurityLevel { get; set; }

    public int? NodeId { get; set; }

    public string Cpid { get; set; }
}