// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EvPlugNet1.Models;

public partial class Role
{
    public int Int { get; set; }

    public byte[] RoleDesc { get; set; }

    public DateTime DateCreate { get; set; }
}