// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EvPlugNet1.Models;

public partial class UserNode
{
    public int Id { get; set; }

    public string SystemUser { get; set; }

    public int? Node { get; set; }

    public DateTime DateCreate { get; set; }
}